version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.0
  maven: circleci/maven@1.3.0

jobs:
  build_and_deploy:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout # check out source code to working directory
      - setup_remote_docker
      - run:
          name: Setup common environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="kevin-repo"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="005751055304.dkr.ecr.us-west-2.amazonaws.com/${ECR_REPOSITORY_NAME}:latest"' >> $BASH_ENV

      - run: mvn dependency:go-offline # gets the project dependencies

      - run: mvn package # run the actual tests

      - run:
          name: Install dependencies for AWS
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
            sudo apt-get install python3-pip
            sudo pip3 install --upgrade awscli

      - run:
          name: Build image
          command: |
            docker build -t $FULL_IMAGE_NAME .

      - run:
          name: Push image
          command: |
            eval $(aws ecr get-login --region us-west-2 --no-include-email)
            docker push $FULL_IMAGE_NAME

workflows:
  build_and_push_image:
    jobs:
      - build_and_deploy
