version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.0
  maven: circleci/maven@1.3.0

jobs:
  build:

    working_directory: /application

    docker:
      - image: openjdk:14

    steps:
      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: application-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies
        -
      - run: mvn package # run the actual tests

      - store_artifacts: # store the uberjar as an artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar

workflows:
  kevin_test:
    jobs:
      - build
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          create-repo: true
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "us-west-2"
          executor: aws-ecr/default
          registry-id: AWS_ECR_REGISTRY_ID
          repo: "kevin-repo"
