version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.0
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      - image: openjdk:14

    working_directory: /tmp
    steps:
      - checkout
      - run:
          name:  Assemble JAR
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: out/artifacts

workflows:
  maven_test:
    jobs:
      - maven/test
  build_and_push_image:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          create-repo: true
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: "us-west-2"
          executor: aws-ecr/default
          registry-id: AWS_ECR_REGISTRY_ID
          repo: "kevin-repo"
